### PR TITLE
Update Derecho software stack

### PR DESCRIPTION
**Pull request by gdicker1**
This is especially to get nvhpc/24.9 since it fixes CAM-MPAS restarts with nvhpc.

NOTE: only gcc+cray-mpich in this update has debug versions of both parallelio and esmf. Other combinations will use the default modules when using DEBUG=true.

Removes intel-classic, limited other modules and would require cray-mpich/8.1.27 remains.

Upgrades:

- gcc/12.2.0 -> gcc/13.2.0
- intel/2023.2.1 -> intel/2024.2.1
- intel-oneapi/2023.2.1 -> intel-oneapi/2024.2.1
- nvhpc/24.3 -> nvhpc/24.9
- cce/15.0.1 -> cce/17.0.1
- cray-mpich/8.1.27 ->  cray-mpich/8.1.29
- mpi-serial/2.3.0 -> mpi-serial/2.5.0
- parallelio/2.6.2 -> parallelio/2.6.3
- esmf/8.6.0 -> esmf/8.7.0 
    - esmf/8.7.0b11-debug (gcc+cray-mpich only)
- cray-libsci/23.02.1.1 -> cray-libsci/24.03.0
    - for cce and gcc compilers

This PR is based on ESMCI/ccs_config_cesm tag 'ccs_config_cesm1.0.7' and is intended to merge after #28

### CODE REVIEW

**Comment by gdicker1** [comment]
Near as I can tell, for better DEBUG=true support we would need 14 modules installed:

- 6 parallelio/2.6.3-debug for
	- cray-mpich/8.1.29
		- nvhpc/24.9, cce/17.0.1
	- mpi-serial/2.5.0
		- intel/2024.2.1, intel-oneapi/2024.2.1, nvhpc, and cce
- 8 esmf/8.7.0-debug (prefer 8.7.0b11-debug since it exists for gcc already)
	- cray-mpich/8.1.29
		- intel, intel-oneapi, nvhpc, cce
	- mpi-serial/2.5.0
		- intel, intel-oneapi, nvhpc, cce

**Comment by gdicker1** [comment]
[20134f3 ](https://github.com/EarthWorksOrg/ccs_config_cesm/commit/20134f3e49a1bce5f8dda73fdb0a699fd58e908d)to [dd14e25 ](https://github.com/EarthWorksOrg/ccs_config_cesm/commit/dd14e252db439a5f2dcd188504b928b21b42ff12) to fix a missing `</modules>` line.

**Comment by gdicker1** [comment]
@dazlich, I can't get CHAOS2000dev compsets to build with gcc/13.2. It's possible there's some new compiler flags that are needed to go with this upgrade.

Not a show stopper, since I'm going to close this PR and make another one that only updates to nvhpc/24.9. (So no work needed on this now). I'll make an EarthWorks Issue about this too.

---

Some output from an ocn.bldlog.\* file (these are the only "Error:" statements I can find):

```
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:74:21:

   74 |          type(c_ptr), value       :: array
      |                     1
Error: Type name 'c_ptr' at (1) is ambiguous
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:77:24:

   77 |          type(c_funptr), value    :: compare ! int (*compare)(const void*, const void*)
      |                        1
Error: Type name 'c_funptr' at (1) is ambiguous
f951: Warning: Nonexistent include directory '/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/gnu/mpich/        nodebug/threads/finclude' [-Wmissing-include-dirs]
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'array' at (1); passed TYPE(c_ptr) to REAL(4)
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'compare' at (1); passed TYPE(c_funptr) to REAL(4)
```

**Comment by dazlich** [comment]
I’ll have a look at some point

On Oct 25, 2024, at 12:10 PM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


@dazlich<https://github.com/dazlich>, I can't get CHAOS2000dev compsets to build with gcc/13.2. It's possible there's some new compiler flags that are needed to go with this upgrade.

Not a show stopper, since I'm going to close this PR and make another one that only updates to nvhpc/24.9. I'll make an EarthWorks Issue about this too.

________________________________

Some output from an ocn.bldlog.* file:

/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:74:21:

   74 |          type(c_ptr), value       :: array
      |                     1
Error: Type name 'c_ptr' at (1) is ambiguous
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:77:24:

   77 |          type(c_funptr), value    :: compare ! int (*compare)(const void*, const void*)
      |                        1
Error: Type name 'c_funptr' at (1) is ambiguous
f951: Warning: Nonexistent include directory '/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/gnu/mpich/        nodebug/threads/finclude' [-Wmissing-include-dirs]
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'array' at (1); passed TYPE(c_ptr) to REAL(4)
/glade/derecho/scratch/gdicker/ew-pr_2024Oct24105100/ewm-2.3.009-77/ERP_Ln9_P256_Vnuopc.mpasa120_oQU120.CHAOS2000dev.derecho_gnu.GC.20241024_105301_2k3ufv/bld/ocn/source/mpas_ocn_okubo_weiss.F:1159:87:

 1159 |       call qsort(c_loc(stats(1)), elemCount, elemSize, c_funloc(compareRealDescending))
      |                                                                                       1
Error: Type mismatch in argument 'compare' at (1); passed TYPE(c_funptr) to REAL(4)

**Pull request closed without merging**
